services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  web:
    build: .
    command: ["/wait-for-db.sh", "daphne", "-b", "0.0.0.0", "-p", "8000", "config.asgi:application"]
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - POSTGRES_DB=comments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
    command: npm run dev -- --host 0.0.0.0
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge