version: '3.9'

services:
  db:
    image: postgres:15
    container_name: comments_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: D:\Projects\Dzen TT\backend
    container_name: comments_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./backend:/backend

    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
